name: Build
on: [ push, pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        output: 
        - chat-server-rust-tokio
        - cryptle-rust
        - echo-tcp-rust-mio
        - echo-tcp-rust-tokio
        - fibonacci-c
        - fibonacci-cpp
        - fibonacci-go
        - fibonacci-rust
        - fibonacci-zig
        - http-rust-tokio

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build ${{ matrix.output }} Enarx package
      run: nix build -L '.#${{ matrix.output }}'
    - run: nix run --inputs-from . 'nixpkgs#coreutils' -- --coreutils-prog=ginstall -p ./result/main.wasm ${{ matrix.output }}.wasm
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output }}.wasm
        path: ${{ matrix.output }}.wasm

    # TODO: Publish packages once 
    # - https://github.com/profianinc/drawbridge/issues/148
    # - https://github.com/enarx/enarx/issues/2048
    # are done
    #- run: enarx package publish "examples/${{ matrix.output }}:$(nix eval --raw '.#${{ matrix.output }}.version')" ./result
